### ISSUE TITLE
TypeError: convert_ilcd() got an unexpected keyword argument 'as_type'

### ISSUE THREAD

**Issue by andreabotti** [ocni-dtu/okobau_example#2]
Traceback (most recent call last):
  File "C:\_GitHub\andreabotti\okobau_example\src\to_epdx.py", line 38, in <module>
    to_epdx()
  File "C:\_GitHub\andreabotti\okobau_example\src\to_epdx.py", line 19, in to_epdx
    epdx_str = epdx.convert_ilcd(epd_str,
TypeError: convert_ilcd() got an unexpected keyword argument 'as_type'

**Comment by ocni-dtu** [comment]
Fixed with the lastest update to this repo
